# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import array
class Ui_MainWindow(object):
        # generating random password  
    def generate_pass(self):
        try:
                length=int(self.pass_length_input.text())
                if (length >= 4 and length<=50):
                        number=list(['0','1','2','3','4','5','6','7','8','9'])
                        character_lower=list(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])
                        character_upper=list(['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'])
                        special=list(['!','@','#','$','%','&','*','~'])
        
                        combined_list=number+character_lower+character_upper+special

                        rand_digit=random.choice(number)
                        rand_upper=random.choice(character_upper)
                        rand_lower=random.choice(character_lower)
                        rand_symbol=random.choice(special)

                        temp_pass=rand_digit+rand_lower+rand_upper+rand_symbol

                        for x in range (length-4):
                                temp_pass=temp_pass+random.choice(combined_list)

                                password_list=array.array('u',temp_pass)
                                random.shuffle(password_list)

                        password=""
                        for x in password_list:
                              password=password+x
                        self.show_pass_output.setText(password)
                        print(f'Password: {password}')

                else:
                        self.showdlg("Enter number above 4 and less than 50")
                        self.pass_length_input.clear()
                        self.show_pass_output.clear()

        except:
                self.showdlg("Enter Numeric digit only")
        # resetting information
        # reset btn function
    def reset(self):
        self.pass_length_input.clear()
        self.show_pass_output.clear()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pass_length_input = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pass_length_input.setFont(font)
        self.pass_length_input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pass_length_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"padding:20px;\n"
"margin-left:50%;\n"
"margin-right:50%;")
        self.pass_length_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pass_length_input.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_length_input.setObjectName("pass_length_input")
        self.verticalLayout.addWidget(self.pass_length_input)
        self.generate_pass_btn = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.generate_pass())
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.generate_pass_btn.setFont(font)
        self.generate_pass_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate_pass_btn.setStyleSheet("background-color: black;\n"
"color:white;\n"
"padding:18px;\n"
"margin-right:225%;\n"
"margin-left:225%;")
        self.generate_pass_btn.setObjectName("generate_pass_btn")
        self.verticalLayout.addWidget(self.generate_pass_btn)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(1)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(-1)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.show_pass_output = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.show_pass_output.setFont(font)
        self.show_pass_output.setFocusPolicy(QtCore.Qt.NoFocus)
        self.show_pass_output.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;\n"
"padding:20px;\n"
"margin-left:50%;\n"
"margin-right:50%;")
        self.show_pass_output.setAlignment(QtCore.Qt.AlignCenter)
        self.show_pass_output.setReadOnly(True)
        self.show_pass_output.setObjectName("show_pass_output")
        self.verticalLayout.addWidget(self.show_pass_output)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.reset())
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reset_btn.setFont(font)
        self.reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_btn.setStyleSheet("background-color: black;\n"
"color:white;\n"
"padding:18px;\n"
"margin-right:225%;\n"
"margin-left:225%;")
        self.reset_btn.setObjectName("reset_btn")
        self.verticalLayout.addWidget(self.reset_btn)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.label.setText(_translate("MainWindow", "PASSWORD GENERATOR"))
        self.label_2.setText(_translate("MainWindow", "PASSWORD LENGTH"))
        self.pass_length_input.setPlaceholderText(_translate("MainWindow", "Enter Password Length"))
        self.generate_pass_btn.setText(_translate("MainWindow", "GENERATE PASSWORD"))
        self.label_3.setText(_translate("MainWindow", "GENERATED PASSWORD"))
        self.show_pass_output.setPlaceholderText(_translate("MainWindow", "Generated Password"))
        self.reset_btn.setText(_translate("MainWindow", "RESET"))
        

    def showdlg(self,msg):
         dialog=QtWidgets.QMessageBox()
         dialog.setWindowTitle("Warning")
         dialog.setText(msg)
         dialog.setStandardButtons(QtWidgets.QMessageBox.Ok)
         dialog.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
