# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

round=1
comp_score=0
player_score=0
class Ui_MainWindow(object):
    def show_Choice(self,choice):
        global comp_score,player_score,round
        computer_choice=list(['Rock','Paper','Scissor'])
        comp_choice=random.choice(computer_choice)
        self.comp_choice_input.setText(comp_choice)

        self.player_choice_input.setText(choice)
        self.round_input.setText(str(round))
        if comp_choice=='Paper':
            if choice=='Paper':
                self.result_input.setText('Tie')
                comp_score=comp_score+0
                player_score=player_score+0
                
            elif choice=='Rock':
                self.result_input.setText('Computer Wins')
                comp_score=comp_score+1
                player_score=player_score+0
                
            else:
                self.result_input.setText("Player Wins")
                comp_score=comp_score+0
                player_score=player_score+1

        elif comp_choice=='Rock':
            if choice=='Paper':
                self.result_input.setText('Player Wins')
                comp_score=comp_score+0
                player_score=player_score+1
                
            elif choice=='Rock':
                self.result_input.setText('Tie')
                comp_score=comp_score+0
                player_score=player_score+0
                
            elif choice=="Scissor":
                self.result_input.setText("Computer Wins")
                comp_score=comp_score+1
                player_score=player_score+0
        
        elif comp_choice=='Scissor':
            if choice=='Paper':
                self.result_input.setText('Computer Wins')
                comp_score=comp_score+1
                player_score=player_score+0
                
            elif choice=='Rock':
                self.result_input.setText('Player Wins')
                comp_score=comp_score+0
                player_score=player_score+1
                
            elif choice=="Scissor":
                self.result_input.setText("Tie")
                comp_score=comp_score+0
                player_score=player_score+0

        self.rock_btn.setDisabled(True)
        self.paper_btn.setDisabled(True)
        self.scissor_btn.setDisabled(True)
        self.player_choice_input.deselect()

        self.player_score_input.display(player_score)
        self.comp_score_input.display(comp_score)
        self.showdlg()

    def play_again(self):
        global round
        round=round+1
        self.paper_btn.setEnabled(True)
        self.scissor_btn.setEnabled(True)
        self.rock_btn.setEnabled(True)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 791, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(86, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(306, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(536, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.player_score_input = QtWidgets.QLCDNumber(self.centralwidget)
        self.player_score_input.setGeometry(QtCore.QRect(116, 150, 101, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.player_score_input.setFont(font)
        self.player_score_input.setObjectName("player_score_input")
        self.comp_score_input = QtWidgets.QLCDNumber(self.centralwidget)
        self.comp_score_input.setGeometry(QtCore.QRect(566, 150, 101, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.comp_score_input.setFont(font)
        self.comp_score_input.setMode(QtWidgets.QLCDNumber.Dec)
        self.comp_score_input.setObjectName("comp_score_input")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 220, 791, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 801, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setLineWidth(4)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 0, 801, 16))
        self.line_2.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.rock_btn = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.show_Choice('Rock'))
        self.rock_btn.setGeometry(QtCore.QRect(120, 290, 171, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rock_btn.setFont(font)
        self.rock_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rock_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.rock_btn.setObjectName("rock_btn")
        self.paper_btn = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.show_Choice('Paper'))
        self.paper_btn.setGeometry(QtCore.QRect(310, 290, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.paper_btn.setFont(font)
        self.paper_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.paper_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.paper_btn.setObjectName("paper_btn")
        self.scissor_btn = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.show_Choice('Scissor'))
        self.scissor_btn.setGeometry(QtCore.QRect(510, 290, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.scissor_btn.setFont(font)
        self.scissor_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scissor_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.scissor_btn.setObjectName("scissor_btn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 380, 171, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-10, 360, 801, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(4)
        self.line_3.setMidLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 380, 221, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.player_choice_input = QtWidgets.QLineEdit(self.centralwidget)
        self.player_choice_input.setGeometry(QtCore.QRect(120, 420, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.player_choice_input.setFont(font)
        self.player_choice_input.setAlignment(QtCore.Qt.AlignCenter)
        self.player_choice_input.setReadOnly(True)
        self.player_choice_input.setObjectName("player_choice_input")
        self.comp_choice_input = QtWidgets.QLineEdit(self.centralwidget)
        self.comp_choice_input.setGeometry(QtCore.QRect(520, 430, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.comp_choice_input.setFont(font)
        self.comp_choice_input.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_choice_input.setReadOnly(True)
        self.comp_choice_input.setObjectName("comp_choice_input")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 440, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.result_input = QtWidgets.QLineEdit(self.centralwidget)
        self.result_input.setGeometry(QtCore.QRect(260, 490, 311, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.result_input.setFont(font)
        self.result_input.setAlignment(QtCore.Qt.AlignCenter)
        self.result_input.setReadOnly(True)
        self.result_input.setObjectName("result_input")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 150, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.round_input = QtWidgets.QLineEdit(self.centralwidget)
        self.round_input.setGeometry(QtCore.QRect(340, 180, 121, 41))
        self.round_input.setAlignment(QtCore.Qt.AlignCenter)
        self.round_input.setReadOnly(True)
        self.round_input.setObjectName("round_input")
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.round_input.setFont(font)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.play_again())
        self.pushButton.setGeometry(QtCore.QRect(610, 530, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.round_input, self.rock_btn)
        MainWindow.setTabOrder(self.rock_btn, self.paper_btn)
        MainWindow.setTabOrder(self.paper_btn, self.scissor_btn)
        MainWindow.setTabOrder(self.scissor_btn, self.player_choice_input)
        MainWindow.setTabOrder(self.player_choice_input, self.comp_choice_input)
        MainWindow.setTabOrder(self.comp_choice_input, self.result_input)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rock, Paper and Scissor Game"))
        self.label.setText(_translate("MainWindow", "ROCK, PAPER AND SCISSOR GAME"))
        self.label_2.setText(_translate("MainWindow", "PLAYER"))
        self.label_3.setText(_translate("MainWindow", "VS"))
        self.label_4.setText(_translate("MainWindow", "COMPUTER"))
        self.label_5.setText(_translate("MainWindow", "ENTER THE CHOICE"))
        self.rock_btn.setText(_translate("MainWindow", "ROCK"))
        self.paper_btn.setText(_translate("MainWindow", "PAPER"))
        self.scissor_btn.setText(_translate("MainWindow", "SCISSOR"))
        self.label_6.setText(_translate("MainWindow", "You Choose"))
        self.label_7.setText(_translate("MainWindow", "Computer Choose"))
        self.label_8.setText(_translate("MainWindow", "RESULT"))
        self.label_9.setText(_translate("MainWindow", "ROUND"))
        self.pushButton.setText(_translate("MainWindow", "Play Again"))
        
    def showdlg(self):
        dialog=QtWidgets.QMessageBox()
        dialog.setWindowTitle("Rules")
        dialog.setText("Press Play Again Button To Continue")
        dialog.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
