# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv

class Ui_MainWindow(object):
    def add_contact(self):
        try:
            name=self.name_input.text()
            phone=int(self.phone_input.text())
            email=self.email_input.text()
            address=self.address_input.text()
            data=list([name,phone,address,email])
            row_count=self.tableWidget.rowCount()
            self.tableWidget.insertRow(row_count)
            for col,value in enumerate(data):
                text=QtWidgets.QTableWidgetItem(str(value))
                self.tableWidget.setItem(row_count,col,text)
                file= open('contact.csv','a')
                file.write(f'{text.text()},')
            file.write('\n')
            file.close()
            self.name_input.clear()
            self.phone_input.clear()
            self.email_input.clear()
            self.address_input.clear()
        except:
            self.showdlg("Cannot add contact")

    def refresh(self):
        with open('contact.csv','r') as f:
            reader=csv.reader(f)
            self.tableWidget.setRowCount(0)
            for row in reader:
                self.tableWidget.insertRow(self.tableWidget.rowCount())
                for col,value in enumerate(row):
                    item=QtWidgets.QTableWidgetItem(value)
                    self.tableWidget.setItem(self.tableWidget.rowCount()-1,col,item)

    def delete_contact(self):
        selected_reow=self.tableWidget.currentRow()
        try:
            with open ('contact.csv','r') as file:
                reader=csv.reader(file)
                rows=list(reader)
            col=len(rows[0])
            rows.pop(selected_reow)
            file.close()
            with open ('contact.csv','w',newline='') as file:
                writer=csv.writer(file)
                writer.writerows(rows)
            file.close()
            self.tableWidget.removeRow(selected_reow)
        except:
            self.showdlg("Cannot delete conatct")

    def update_contact(self):
        try:
            selected_row=self.tableWidget.currentRow()
            with open ('contact.csv','r') as file:
                reader=csv.reader(file)
                rows=list(reader)
            col=len(rows[0])
            rows.pop(selected_row)
            file.close()
            with open ('contact.csv','w',newline='') as file:
                writer=csv.writer(file)
                writer.writerows(rows)
            file.close()

            selected_data=[]
            self.showdlg("Press Add Contact after Modification")
            for col in range(self.tableWidget.columnCount()):
                item=self.tableWidget.item(selected_row,col)
                selected_data.append(item.text())
                # print(selected_data)
            name=selected_data[0]
            phone=selected_data[1]
            address=selected_data[2]
            email=selected_data[3]

            self.name_input.setText(name)
            self.phone_input.setText(phone)
            self.address_input.setText(address)
            self.email_input.setText(email)
            self.tableWidget.removeRow(selected_row)
        except:
            self.showdlg("Cannot Update Data")

    def search(self):
        try:
            text,ok=QtWidgets.QInputDialog.getText(MainWindow,"Search Bar","Enter the Name Or Phone")
            if ok:
                with open ('contact.csv','r') as file:
                    reader=csv.reader(file)
                    for row in reader:
                        # print(row)
                        # print(text)
                        if (row[0]==text) or (row[1]==text):
                            self.name_input.setText(row[0])
                            self.phone_input.setText(row[1])
                            self.address_input.setText(row[2])
                            self.email_input.setText(row[3])
                        else:
                            self.showdlg("No Record Found")
                file.close()
        except:
            self.showdlg("No Record Found")
            
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 839)
        font = QtGui.QFont()
        font.setPointSize(3)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QFrame{\n"
"background-color: rgb(213, 213, 213);\n"
"}\n"
"/*QLabel{\n"
"color:black;\n"
"font-size:14px;\n"
"}\n"
"*/\n"
"#label\n"
"{\n"
"color:black;\n"
"font-size:25px;\n"
"}\n"
"QLineEdit{\n"
"height:35px;\n"
"margin-top:10px;\n"
"font-size:15px;\n"
"border:2px solid grey;\n"
"padding: 5px 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"border:2px solid red;\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid green;\n"
"}\n"
"QPushButton{\n"
"margin-top:15px;\n"
"height:50px;\n"
"width:100px;\n"
"color:white;\n"
"background-color:black;\n"
"border-radius:15px;\n"
"font-size:18px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid green;\n"
"color:white;\n"
"background-color:blue;\n"
"}\n"
"QPushButton:focus{\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 0, 1081, 20))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 1081, 51))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(10, 60, 1081, 31))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 1081, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(10, 130, 1071, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(610, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(610, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(10, 80, 1081, 21))
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.email_input = QtWidgets.QLineEdit(self.frame)
        self.email_input.setGeometry(QtCore.QRect(690, 210, 301, 41))
        self.email_input.setObjectName("email_input")
        self.address_input = QtWidgets.QLineEdit(self.frame)
        self.address_input.setGeometry(QtCore.QRect(140, 210, 331, 41))
        self.address_input.setObjectName("address_input")
        self.search_btn = QtWidgets.QPushButton(self.frame,clicked=lambda:self.search())
        self.search_btn.setGeometry(QtCore.QRect(50, 290, 191, 61))
        self.search_btn.setObjectName("search_btn")
        self.clear_btn = QtWidgets.QPushButton(self.frame)
        self.clear_btn.setGeometry(QtCore.QRect(430, 380, 191, 61))
        self.clear_btn.setObjectName("clear_btn")
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(10, 450, 1081, 20))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(4)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(0, 480, 1081, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(10, 500, 1081, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 520, 1081, 301))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(262)
        self.name_input = QtWidgets.QLineEdit(self.frame)
        self.name_input.setGeometry(QtCore.QRect(140, 140, 331, 41))
        self.name_input.setObjectName("name_input")
        self.phone_input = QtWidgets.QLineEdit(self.frame)
        self.phone_input.setGeometry(QtCore.QRect(690, 140, 301, 41))
        self.phone_input.setObjectName("phone_input")
        self.add_contact_btn = QtWidgets.QPushButton(self.frame,clicked=lambda:self.add_contact())
        self.add_contact_btn.setGeometry(QtCore.QRect(430, 290, 191, 61))
        self.add_contact_btn.setObjectName("add_contact_btn")
        self.delete_contact_btn = QtWidgets.QPushButton(self.frame,clicked=lambda:self.delete_contact())
        self.delete_contact_btn.setGeometry(QtCore.QRect(800, 290, 191, 61))
        self.delete_contact_btn.setObjectName("delete_contact_btn")
        self.update_btn_4 = QtWidgets.QPushButton(self.frame,clicked=lambda:self.update_contact())
        self.update_btn_4.setGeometry(QtCore.QRect(50, 380, 191, 61))
        self.update_btn_4.setObjectName("update_btn_4")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.clear_btn.clicked.connect(self.address_input.clear) # type: ignore
        self.clear_btn.clicked.connect(self.email_input.clear) # type: ignore
        self.clear_btn.clicked.connect(self.phone_input.clear) # type: ignore
        self.clear_btn.clicked.connect(self.name_input.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.name_input, self.phone_input)
        MainWindow.setTabOrder(self.phone_input, self.address_input)
        MainWindow.setTabOrder(self.address_input, self.email_input)
        MainWindow.setTabOrder(self.email_input, self.search_btn)
        MainWindow.setTabOrder(self.search_btn, self.add_contact_btn)
        MainWindow.setTabOrder(self.add_contact_btn, self.delete_contact_btn)
        MainWindow.setTabOrder(self.delete_contact_btn, self.update_btn_4)
        MainWindow.setTabOrder(self.update_btn_4, self.clear_btn)
        MainWindow.setTabOrder(self.clear_btn, self.tableWidget)
        # self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.refresh()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact Book"))
        self.label.setText(_translate("MainWindow", "CONTACT BOOK"))
        self.label_2.setText(_translate("MainWindow", " Contact Information"))
        self.label_4.setText(_translate("MainWindow", "Name :"))
        self.label_5.setText(_translate("MainWindow", "Phone :"))
        self.label_6.setText(_translate("MainWindow", "Email :"))
        self.label_8.setText(_translate("MainWindow", "Address : "))
        self.search_btn.setText(_translate("MainWindow", "SEARCH"))
        self.search_btn.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.clear_btn.setText(_translate("MainWindow", "CLEAR"))
        self.clear_btn.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.label_16.setText(_translate("MainWindow", "View Information"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PHONE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "EMAIL"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ADDRESS"))
        self.add_contact_btn.setText(_translate("MainWindow", "ADD CONTACT"))
        self.add_contact_btn.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.delete_contact_btn.setText(_translate("MainWindow", "DELETE CONTACT"))
        self.delete_contact_btn.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.update_btn_4.setText(_translate("MainWindow", "UPDATE CONTACT"))
        self.update_btn_4.setShortcut(_translate("MainWindow", "Ctrl+Del"))

    def showdlg(self,msg):
        dialog=QtWidgets.QMessageBox()
        dialog.setWindowTitle("Information")
        dialog.setText(msg)
        dialog.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
